fragment JoinParts on Join {
  __typename
  seo {
    __typename
    title
    description
    keywords
  }
  apply {
    __typename
    title
    button {
      __typename
      text
      url
    }
  }
  faqs {
    __typename
    question
    answer
    defaultOpen
  }
}

fragment PeopleParts on People {
  __typename
  images {
    __typename
    heroes {
      __typename
      src
      alt
      title
    }
  }
  people {
    __typename
    name
    url
    img
    roles
    status
    start
    end
    affiliation
    now
  }
}

fragment AboutParts on About {
  __typename
  communityResearch {
    __typename
    title
    description
    video
  }
  studioTime {
    __typename
    title
    description
    image
    imageAlt
    imageCaption
    buttonText
    buttonLink
  }
  learningOutcomes {
    __typename
    title
    items {
      __typename
      title
      description
    }
    alumni {
      __typename
      name
      title
      quote
      img
    }
  }
  events {
    __typename
    title1
    description1
    image1
    image1Alt
    title2
    description2
    image2
    image2Alt
    ctaTitle
    buttonText
    buttonLink
  }
  labHappenings {
    __typename
    title
    description
    images {
      __typename
      src
      alt
    }
  }
}
