fragment JoinParts on Join {
  __typename
  seo {
    __typename
    title
    description
    keywords
  }
  apply {
    __typename
    title
    button {
      __typename
      text
      url
    }
  }
  faqs {
    __typename
    question
    answer
    defaultOpen
  }
}

fragment PeopleParts on People {
  __typename
  images {
    __typename
    heroes {
      __typename
      src
      alt
      title
    }
  }
  people {
    __typename
    name
    url
    img
    roles
    status
    start
    end
    affiliation
    now
  }
}
