fragment RoutesParts on Routes {
  __typename
  home {
    __typename
    label
    heroImage
    heroTitle
    heroSubtitle
  }
  about {
    __typename
    label
    heroImage
    heroTitle
  }
  research {
    __typename
    label
    heroImage
    heroTitle
  }
  people {
    __typename
    label
    heroImage
    heroTitle
  }
  courses {
    __typename
    label
    heroImage
    heroTitle
  }
  sponsors {
    __typename
    label
    heroImage
    heroTitle
  }
  join {
    __typename
    label
    heroImage
    heroTitle
  }
}

fragment JoinParts on Join {
  __typename
  seo {
    __typename
    title
    description
    keywords
  }
  apply {
    __typename
    title
    button {
      __typename
      text
      url
    }
  }
  faqs {
    __typename
    question
    answer
    defaultOpen
  }
}

fragment PeopleParts on People {
  __typename
  seo {
    __typename
    current {
      __typename
      title
      description
      keywords
    }
    alumni {
      __typename
      title
      description
      keywords
    }
    collaborators {
      __typename
      title
      description
      keywords
    }
  }
  people {
    __typename
    name
    url
    img
    roles
    status
    start
    end
    affiliation
    now
  }
}
