//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  join: Join;
  joinConnection: JoinConnection;
  people: People;
  peopleConnection: PeopleConnection;
  about: About;
  aboutConnection: AboutConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryJoinArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryJoinConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<JoinFilter>;
};


export type QueryPeopleArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPeopleConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PeopleFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};

export type DocumentFilter = {
  join?: InputMaybe<JoinFilter>;
  people?: InputMaybe<PeopleFilter>;
  about?: InputMaybe<AboutFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Join | People | About | Folder;

export type JoinSeo = {
  __typename?: 'JoinSeo';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  keywords: Scalars['String']['output'];
};

export type JoinApplyButton = {
  __typename?: 'JoinApplyButton';
  text: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type JoinApply = {
  __typename?: 'JoinApply';
  title: Scalars['String']['output'];
  button?: Maybe<JoinApplyButton>;
};

export type JoinFaqs = {
  __typename?: 'JoinFaqs';
  question: Scalars['String']['output'];
  answer: Scalars['String']['output'];
  defaultOpen?: Maybe<Scalars['Boolean']['output']>;
};

export type Join = Node & Document & {
  __typename?: 'Join';
  seo?: Maybe<JoinSeo>;
  apply?: Maybe<JoinApply>;
  faqs?: Maybe<Array<Maybe<JoinFaqs>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type JoinSeoFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
};

export type JoinApplyButtonFilter = {
  text?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type JoinApplyFilter = {
  title?: InputMaybe<StringFilter>;
  button?: InputMaybe<JoinApplyButtonFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type JoinFaqsFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
  defaultOpen?: InputMaybe<BooleanFilter>;
};

export type JoinFilter = {
  seo?: InputMaybe<JoinSeoFilter>;
  apply?: InputMaybe<JoinApplyFilter>;
  faqs?: InputMaybe<JoinFaqsFilter>;
};

export type JoinConnectionEdges = {
  __typename?: 'JoinConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Join>;
};

export type JoinConnection = Connection & {
  __typename?: 'JoinConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<JoinConnectionEdges>>>;
};

export type PeopleImagesHeroes = {
  __typename?: 'PeopleImagesHeroes';
  src: Scalars['String']['output'];
  alt: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
};

export type PeopleImages = {
  __typename?: 'PeopleImages';
  heroes?: Maybe<Array<Maybe<PeopleImagesHeroes>>>;
};

export type PeoplePeople = {
  __typename?: 'PeoplePeople';
  name: Scalars['String']['output'];
  url?: Maybe<Scalars['String']['output']>;
  img?: Maybe<Scalars['String']['output']>;
  roles?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  status: Scalars['String']['output'];
  start?: Maybe<Scalars['Float']['output']>;
  end?: Maybe<Scalars['Float']['output']>;
  affiliation: Scalars['String']['output'];
  now?: Maybe<Scalars['String']['output']>;
};

export type People = Node & Document & {
  __typename?: 'People';
  images?: Maybe<PeopleImages>;
  people?: Maybe<Array<Maybe<PeoplePeople>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PeopleImagesHeroesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
};

export type PeopleImagesFilter = {
  heroes?: InputMaybe<PeopleImagesHeroesFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type PeoplePeopleFilter = {
  name?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  img?: InputMaybe<ImageFilter>;
  roles?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  start?: InputMaybe<NumberFilter>;
  end?: InputMaybe<NumberFilter>;
  affiliation?: InputMaybe<StringFilter>;
  now?: InputMaybe<StringFilter>;
};

export type PeopleFilter = {
  images?: InputMaybe<PeopleImagesFilter>;
  people?: InputMaybe<PeoplePeopleFilter>;
};

export type PeopleConnectionEdges = {
  __typename?: 'PeopleConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<People>;
};

export type PeopleConnection = Connection & {
  __typename?: 'PeopleConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PeopleConnectionEdges>>>;
};

export type AboutCommunityResearch = {
  __typename?: 'AboutCommunityResearch';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  video?: Maybe<Scalars['String']['output']>;
};

export type AboutStudioTime = {
  __typename?: 'AboutStudioTime';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  imageCaption?: Maybe<Scalars['String']['output']>;
  buttonText?: Maybe<Scalars['String']['output']>;
  buttonLink?: Maybe<Scalars['String']['output']>;
};

export type AboutLearningOutcomesItems = {
  __typename?: 'AboutLearningOutcomesItems';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type AboutLearningOutcomesAlumni = {
  __typename?: 'AboutLearningOutcomesAlumni';
  name?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  quote?: Maybe<Scalars['String']['output']>;
  img?: Maybe<Scalars['String']['output']>;
};

export type AboutLearningOutcomes = {
  __typename?: 'AboutLearningOutcomes';
  title: Scalars['String']['output'];
  items?: Maybe<Array<Maybe<AboutLearningOutcomesItems>>>;
  alumni?: Maybe<Array<Maybe<AboutLearningOutcomesAlumni>>>;
};

export type AboutEvents = {
  __typename?: 'AboutEvents';
  title1?: Maybe<Scalars['String']['output']>;
  description1?: Maybe<Scalars['String']['output']>;
  image1?: Maybe<Scalars['String']['output']>;
  image1Alt?: Maybe<Scalars['String']['output']>;
  title2?: Maybe<Scalars['String']['output']>;
  description2?: Maybe<Scalars['String']['output']>;
  image2?: Maybe<Scalars['String']['output']>;
  image2Alt?: Maybe<Scalars['String']['output']>;
  ctaTitle?: Maybe<Scalars['String']['output']>;
  buttonText?: Maybe<Scalars['String']['output']>;
  buttonLink?: Maybe<Scalars['String']['output']>;
};

export type AboutLabHappeningsImages = {
  __typename?: 'AboutLabHappeningsImages';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type AboutLabHappenings = {
  __typename?: 'AboutLabHappenings';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  images?: Maybe<Array<Maybe<AboutLabHappeningsImages>>>;
};

export type About = Node & Document & {
  __typename?: 'About';
  communityResearch?: Maybe<AboutCommunityResearch>;
  studioTime?: Maybe<AboutStudioTime>;
  learningOutcomes?: Maybe<AboutLearningOutcomes>;
  events?: Maybe<AboutEvents>;
  labHappenings?: Maybe<AboutLabHappenings>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutCommunityResearchFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  video?: InputMaybe<StringFilter>;
};

export type AboutStudioTimeFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  imageCaption?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
  buttonLink?: InputMaybe<StringFilter>;
};

export type AboutLearningOutcomesItemsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type AboutLearningOutcomesAlumniFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
  img?: InputMaybe<ImageFilter>;
};

export type AboutLearningOutcomesFilter = {
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<AboutLearningOutcomesItemsFilter>;
  alumni?: InputMaybe<AboutLearningOutcomesAlumniFilter>;
};

export type AboutEventsFilter = {
  title1?: InputMaybe<StringFilter>;
  description1?: InputMaybe<StringFilter>;
  image1?: InputMaybe<ImageFilter>;
  image1Alt?: InputMaybe<StringFilter>;
  title2?: InputMaybe<StringFilter>;
  description2?: InputMaybe<StringFilter>;
  image2?: InputMaybe<ImageFilter>;
  image2Alt?: InputMaybe<StringFilter>;
  ctaTitle?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
  buttonLink?: InputMaybe<StringFilter>;
};

export type AboutLabHappeningsImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type AboutLabHappeningsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  images?: InputMaybe<AboutLabHappeningsImagesFilter>;
};

export type AboutFilter = {
  communityResearch?: InputMaybe<AboutCommunityResearchFilter>;
  studioTime?: InputMaybe<AboutStudioTimeFilter>;
  learningOutcomes?: InputMaybe<AboutLearningOutcomesFilter>;
  events?: InputMaybe<AboutEventsFilter>;
  labHappenings?: InputMaybe<AboutLabHappeningsFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateJoin: Join;
  createJoin: Join;
  updatePeople: People;
  createPeople: People;
  updateAbout: About;
  createAbout: About;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateJoinArgs = {
  relativePath: Scalars['String']['input'];
  params: JoinMutation;
};


export type MutationCreateJoinArgs = {
  relativePath: Scalars['String']['input'];
  params: JoinMutation;
};


export type MutationUpdatePeopleArgs = {
  relativePath: Scalars['String']['input'];
  params: PeopleMutation;
};


export type MutationCreatePeopleArgs = {
  relativePath: Scalars['String']['input'];
  params: PeopleMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};

export type DocumentUpdateMutation = {
  join?: InputMaybe<JoinMutation>;
  people?: InputMaybe<PeopleMutation>;
  about?: InputMaybe<AboutMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  join?: InputMaybe<JoinMutation>;
  people?: InputMaybe<PeopleMutation>;
  about?: InputMaybe<AboutMutation>;
};

export type JoinSeoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  keywords?: InputMaybe<Scalars['String']['input']>;
};

export type JoinApplyButtonMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type JoinApplyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  button?: InputMaybe<JoinApplyButtonMutation>;
};

export type JoinFaqsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
  defaultOpen?: InputMaybe<Scalars['Boolean']['input']>;
};

export type JoinMutation = {
  seo?: InputMaybe<JoinSeoMutation>;
  apply?: InputMaybe<JoinApplyMutation>;
  faqs?: InputMaybe<Array<InputMaybe<JoinFaqsMutation>>>;
};

export type PeopleImagesHeroesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
};

export type PeopleImagesMutation = {
  heroes?: InputMaybe<Array<InputMaybe<PeopleImagesHeroesMutation>>>;
};

export type PeoplePeopleMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  img?: InputMaybe<Scalars['String']['input']>;
  roles?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  status?: InputMaybe<Scalars['String']['input']>;
  start?: InputMaybe<Scalars['Float']['input']>;
  end?: InputMaybe<Scalars['Float']['input']>;
  affiliation?: InputMaybe<Scalars['String']['input']>;
  now?: InputMaybe<Scalars['String']['input']>;
};

export type PeopleMutation = {
  images?: InputMaybe<PeopleImagesMutation>;
  people?: InputMaybe<Array<InputMaybe<PeoplePeopleMutation>>>;
};

export type AboutCommunityResearchMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  video?: InputMaybe<Scalars['String']['input']>;
};

export type AboutStudioTimeMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  imageCaption?: InputMaybe<Scalars['String']['input']>;
  buttonText?: InputMaybe<Scalars['String']['input']>;
  buttonLink?: InputMaybe<Scalars['String']['input']>;
};

export type AboutLearningOutcomesItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type AboutLearningOutcomesAlumniMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
  img?: InputMaybe<Scalars['String']['input']>;
};

export type AboutLearningOutcomesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<AboutLearningOutcomesItemsMutation>>>;
  alumni?: InputMaybe<Array<InputMaybe<AboutLearningOutcomesAlumniMutation>>>;
};

export type AboutEventsMutation = {
  title1?: InputMaybe<Scalars['String']['input']>;
  description1?: InputMaybe<Scalars['String']['input']>;
  image1?: InputMaybe<Scalars['String']['input']>;
  image1Alt?: InputMaybe<Scalars['String']['input']>;
  title2?: InputMaybe<Scalars['String']['input']>;
  description2?: InputMaybe<Scalars['String']['input']>;
  image2?: InputMaybe<Scalars['String']['input']>;
  image2Alt?: InputMaybe<Scalars['String']['input']>;
  ctaTitle?: InputMaybe<Scalars['String']['input']>;
  buttonText?: InputMaybe<Scalars['String']['input']>;
  buttonLink?: InputMaybe<Scalars['String']['input']>;
};

export type AboutLabHappeningsImagesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type AboutLabHappeningsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<AboutLabHappeningsImagesMutation>>>;
};

export type AboutMutation = {
  communityResearch?: InputMaybe<AboutCommunityResearchMutation>;
  studioTime?: InputMaybe<AboutStudioTimeMutation>;
  learningOutcomes?: InputMaybe<AboutLearningOutcomesMutation>;
  events?: InputMaybe<AboutEventsMutation>;
  labHappenings?: InputMaybe<AboutLabHappeningsMutation>;
};

export type JoinPartsFragment = { __typename: 'Join', seo?: { __typename: 'JoinSeo', title: string, description: string, keywords: string } | null, apply?: { __typename: 'JoinApply', title: string, button?: { __typename: 'JoinApplyButton', text: string, url: string } | null } | null, faqs?: Array<{ __typename: 'JoinFaqs', question: string, answer: string, defaultOpen?: boolean | null } | null> | null };

export type PeoplePartsFragment = { __typename: 'People', images?: { __typename: 'PeopleImages', heroes?: Array<{ __typename: 'PeopleImagesHeroes', src: string, alt: string, title?: string | null } | null> | null } | null, people?: Array<{ __typename: 'PeoplePeople', name: string, url?: string | null, img?: string | null, roles?: Array<string | null> | null, status: string, start?: number | null, end?: number | null, affiliation: string, now?: string | null } | null> | null };

export type AboutPartsFragment = { __typename: 'About', communityResearch?: { __typename: 'AboutCommunityResearch', title?: string | null, description?: string | null, video?: string | null } | null, studioTime?: { __typename: 'AboutStudioTime', title?: string | null, description?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, buttonText?: string | null, buttonLink?: string | null } | null, learningOutcomes?: { __typename: 'AboutLearningOutcomes', title: string, items?: Array<{ __typename: 'AboutLearningOutcomesItems', title?: string | null, description?: string | null } | null> | null, alumni?: Array<{ __typename: 'AboutLearningOutcomesAlumni', name?: string | null, title?: string | null, quote?: string | null, img?: string | null } | null> | null } | null, events?: { __typename: 'AboutEvents', title1?: string | null, description1?: string | null, image1?: string | null, image1Alt?: string | null, title2?: string | null, description2?: string | null, image2?: string | null, image2Alt?: string | null, ctaTitle?: string | null, buttonText?: string | null, buttonLink?: string | null } | null, labHappenings?: { __typename: 'AboutLabHappenings', title?: string | null, description?: string | null, images?: Array<{ __typename: 'AboutLabHappeningsImages', src?: string | null, alt?: string | null } | null> | null } | null };

export type JoinQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type JoinQuery = { __typename?: 'Query', join: { __typename: 'Join', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'JoinSeo', title: string, description: string, keywords: string } | null, apply?: { __typename: 'JoinApply', title: string, button?: { __typename: 'JoinApplyButton', text: string, url: string } | null } | null, faqs?: Array<{ __typename: 'JoinFaqs', question: string, answer: string, defaultOpen?: boolean | null } | null> | null } };

export type JoinConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<JoinFilter>;
}>;


export type JoinConnectionQuery = { __typename?: 'Query', joinConnection: { __typename?: 'JoinConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'JoinConnectionEdges', cursor: string, node?: { __typename: 'Join', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'JoinSeo', title: string, description: string, keywords: string } | null, apply?: { __typename: 'JoinApply', title: string, button?: { __typename: 'JoinApplyButton', text: string, url: string } | null } | null, faqs?: Array<{ __typename: 'JoinFaqs', question: string, answer: string, defaultOpen?: boolean | null } | null> | null } | null } | null> | null } };

export type PeopleQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PeopleQuery = { __typename?: 'Query', people: { __typename: 'People', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images?: { __typename: 'PeopleImages', heroes?: Array<{ __typename: 'PeopleImagesHeroes', src: string, alt: string, title?: string | null } | null> | null } | null, people?: Array<{ __typename: 'PeoplePeople', name: string, url?: string | null, img?: string | null, roles?: Array<string | null> | null, status: string, start?: number | null, end?: number | null, affiliation: string, now?: string | null } | null> | null } };

export type PeopleConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PeopleFilter>;
}>;


export type PeopleConnectionQuery = { __typename?: 'Query', peopleConnection: { __typename?: 'PeopleConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PeopleConnectionEdges', cursor: string, node?: { __typename: 'People', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images?: { __typename: 'PeopleImages', heroes?: Array<{ __typename: 'PeopleImagesHeroes', src: string, alt: string, title?: string | null } | null> | null } | null, people?: Array<{ __typename: 'PeoplePeople', name: string, url?: string | null, img?: string | null, roles?: Array<string | null> | null, status: string, start?: number | null, end?: number | null, affiliation: string, now?: string | null } | null> | null } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, communityResearch?: { __typename: 'AboutCommunityResearch', title?: string | null, description?: string | null, video?: string | null } | null, studioTime?: { __typename: 'AboutStudioTime', title?: string | null, description?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, buttonText?: string | null, buttonLink?: string | null } | null, learningOutcomes?: { __typename: 'AboutLearningOutcomes', title: string, items?: Array<{ __typename: 'AboutLearningOutcomesItems', title?: string | null, description?: string | null } | null> | null, alumni?: Array<{ __typename: 'AboutLearningOutcomesAlumni', name?: string | null, title?: string | null, quote?: string | null, img?: string | null } | null> | null } | null, events?: { __typename: 'AboutEvents', title1?: string | null, description1?: string | null, image1?: string | null, image1Alt?: string | null, title2?: string | null, description2?: string | null, image2?: string | null, image2Alt?: string | null, ctaTitle?: string | null, buttonText?: string | null, buttonLink?: string | null } | null, labHappenings?: { __typename: 'AboutLabHappenings', title?: string | null, description?: string | null, images?: Array<{ __typename: 'AboutLabHappeningsImages', src?: string | null, alt?: string | null } | null> | null } | null } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, communityResearch?: { __typename: 'AboutCommunityResearch', title?: string | null, description?: string | null, video?: string | null } | null, studioTime?: { __typename: 'AboutStudioTime', title?: string | null, description?: string | null, image?: string | null, imageAlt?: string | null, imageCaption?: string | null, buttonText?: string | null, buttonLink?: string | null } | null, learningOutcomes?: { __typename: 'AboutLearningOutcomes', title: string, items?: Array<{ __typename: 'AboutLearningOutcomesItems', title?: string | null, description?: string | null } | null> | null, alumni?: Array<{ __typename: 'AboutLearningOutcomesAlumni', name?: string | null, title?: string | null, quote?: string | null, img?: string | null } | null> | null } | null, events?: { __typename: 'AboutEvents', title1?: string | null, description1?: string | null, image1?: string | null, image1Alt?: string | null, title2?: string | null, description2?: string | null, image2?: string | null, image2Alt?: string | null, ctaTitle?: string | null, buttonText?: string | null, buttonLink?: string | null } | null, labHappenings?: { __typename: 'AboutLabHappenings', title?: string | null, description?: string | null, images?: Array<{ __typename: 'AboutLabHappeningsImages', src?: string | null, alt?: string | null } | null> | null } | null } | null } | null> | null } };

export const JoinPartsFragmentDoc = gql`
    fragment JoinParts on Join {
  __typename
  seo {
    __typename
    title
    description
    keywords
  }
  apply {
    __typename
    title
    button {
      __typename
      text
      url
    }
  }
  faqs {
    __typename
    question
    answer
    defaultOpen
  }
}
    `;
export const PeoplePartsFragmentDoc = gql`
    fragment PeopleParts on People {
  __typename
  images {
    __typename
    heroes {
      __typename
      src
      alt
      title
    }
  }
  people {
    __typename
    name
    url
    img
    roles
    status
    start
    end
    affiliation
    now
  }
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  communityResearch {
    __typename
    title
    description
    video
  }
  studioTime {
    __typename
    title
    description
    image
    imageAlt
    imageCaption
    buttonText
    buttonLink
  }
  learningOutcomes {
    __typename
    title
    items {
      __typename
      title
      description
    }
    alumni {
      __typename
      name
      title
      quote
      img
    }
  }
  events {
    __typename
    title1
    description1
    image1
    image1Alt
    title2
    description2
    image2
    image2Alt
    ctaTitle
    buttonText
    buttonLink
  }
  labHappenings {
    __typename
    title
    description
    images {
      __typename
      src
      alt
    }
  }
}
    `;
export const JoinDocument = gql`
    query join($relativePath: String!) {
  join(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...JoinParts
  }
}
    ${JoinPartsFragmentDoc}`;
export const JoinConnectionDocument = gql`
    query joinConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: JoinFilter) {
  joinConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...JoinParts
      }
    }
  }
}
    ${JoinPartsFragmentDoc}`;
export const PeopleDocument = gql`
    query people($relativePath: String!) {
  people(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PeopleParts
  }
}
    ${PeoplePartsFragmentDoc}`;
export const PeopleConnectionDocument = gql`
    query peopleConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PeopleFilter) {
  peopleConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PeopleParts
      }
    }
  }
}
    ${PeoplePartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      join(variables: JoinQueryVariables, options?: C): Promise<{data: JoinQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JoinQueryVariables, query: string}> {
        return requester<{data: JoinQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JoinQueryVariables, query: string}, JoinQueryVariables>(JoinDocument, variables, options);
      },
    joinConnection(variables?: JoinConnectionQueryVariables, options?: C): Promise<{data: JoinConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JoinConnectionQueryVariables, query: string}> {
        return requester<{data: JoinConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JoinConnectionQueryVariables, query: string}, JoinConnectionQueryVariables>(JoinConnectionDocument, variables, options);
      },
    people(variables: PeopleQueryVariables, options?: C): Promise<{data: PeopleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeopleQueryVariables, query: string}> {
        return requester<{data: PeopleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeopleQueryVariables, query: string}, PeopleQueryVariables>(PeopleDocument, variables, options);
      },
    peopleConnection(variables?: PeopleConnectionQueryVariables, options?: C): Promise<{data: PeopleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeopleConnectionQueryVariables, query: string}> {
        return requester<{data: PeopleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeopleConnectionQueryVariables, query: string}, PeopleConnectionQueryVariables>(PeopleConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  